# Workflow to verify that yaml-substitution are working correctly.

name: "YAML Substitution Sanity Check"

on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    paths:
      - 'emulation_system/**'
      - '.github/workflows/yaml-sub-sanity-check.yaml'
      - '.github/actions/**'
      - 'action.yaml'
      - 'scripts/makefile/helper_scripts/**'
      - 'docker/**'
      - './Makefile'
  workflow_dispatch:
    inputs:
      cache-break:
        description: Break the Cache
        required: false
        default: default

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yaml-sub-sanity-check:
    runs-on: "ubuntu-20.04"
    name: YAML Substitution Sanity Check
    steps:
      - name: Checkout opentrons-emulation
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      # Only change `main` in Opentrons/opentrons-emulation@main
      # if making changes to .github/actions or action.yaml
      - name: Setup Emulation
        uses: Opentrons/opentrons-emulation@main
        with:
          cache-break: ${{ github.event.inputs.cache-break }}
          command: setup-python-only

      # Only change `main` in Opentrons/opentrons-emulation@main
      # if making changes to .github/actions or action.yaml
      - name: YAML Substitution
        uses: Opentrons/opentrons-emulation@main
        with:
          command: yaml-sub
          substitutions: >-
            [
              ["otie", "exposed-port", "5000"]
            ]
          input-file: ${{ github.workspace }}/samples/ot3/ot3_remote.yaml
          output-file-location: ${{ github.workspace }}/output.yaml

      - name: See file
        run: cat ${{ github.workspace }}/output.yaml
